"""Multiscale noisy-symbol prediction task.

The task is a small probabilistic language generated by independent binary
latent variables.  Latent component ``k`` persists with pole
``rho_k = exp(-1 / tau_k)`` and is observed through an independent binary
sign-flip channel.  Three components therefore define an eight-symbol
vocabulary while retaining a component-wise loss decomposition.

Models receive observations through time ``t`` and predict the observation at
``t + 1``.  The module also exposes finite-context optimal-linear and
Bayes-optimal reference losses for each component.
"""

from __future__ import annotations

from functools import lru_cache
from typing import Iterable

import lightning as L
import numpy as np
import torch
from torch.utils.data import DataLoader, IterableDataset, TensorDataset


def _normalize_timescales(
    timescales: float | Iterable[float], n_components: int
) -> list[float]:
    if isinstance(timescales, (int, float)):
        values = [float(timescales)] * n_components
    else:
        values = [float(value) for value in timescales]
    if len(values) != n_components:
        raise ValueError(
            f"len(timescales)={len(values)} does not match "
            f"n_components={n_components}"
        )
    if any(value <= 0.0 for value in values):
        raise ValueError("all timescales must be positive")
    return values


def timescale_to_pole(timescale: float) -> float:
    """Return the discrete-time autocorrelation pole for ``timescale``."""
    if timescale <= 0.0:
        raise ValueError("timescale must be positive")
    return float(np.exp(-1.0 / float(timescale)))


def generate_multiscale_hmm_sequences(
    num_trajectories: int,
    num_time_steps: int,
    timescales: Iterable[float],
    observation_flip_probability: float = 0.15,
    rng: np.random.Generator | None = None,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Generate next-symbol prediction trajectories.

    Args:
        num_trajectories: Number of independent trajectories.
        num_time_steps: Number of input/target positions.  Internally, one
            additional observation is generated for the next-step target.
        timescales: One latent persistence timescale per component.
        observation_flip_probability: Probability that an observed sign is
            flipped relative to its latent sign.
        rng: Optional NumPy generator.

    Returns:
        inputs: Observed symbols through time ``t``, shape ``[B, T, C]``.
        latent_targets: Latent state at ``t + 1``, shape ``[B, T, C]``.
        targets: Observed symbol at ``t + 1``, shape ``[B, T, C]``.
    """
    if num_trajectories <= 0 or num_time_steps <= 0:
        raise ValueError("num_trajectories and num_time_steps must be positive")
    if not 0.0 <= observation_flip_probability <= 0.5:
        raise ValueError("observation_flip_probability must lie in [0, 0.5]")

    tau = np.asarray(list(timescales), dtype=np.float64)
    if tau.ndim != 1 or tau.size == 0 or np.any(tau <= 0.0):
        raise ValueError("timescales must be a non-empty sequence of positives")
    if rng is None:
        rng = np.random.default_rng()

    batch_size = int(num_trajectories)
    sequence_length = int(num_time_steps) + 1
    n_components = int(tau.size)
    resample_probability = 1.0 - np.exp(-1.0 / tau)

    latent = np.empty(
        (batch_size, sequence_length, n_components), dtype=np.float32
    )
    latent[:, 0, :] = rng.choice(
        np.asarray([-1.0, 1.0], dtype=np.float32),
        size=(batch_size, n_components),
    )
    for time_index in range(1, sequence_length):
        previous = latent[:, time_index - 1, :]
        resample = rng.random((batch_size, n_components)) < resample_probability
        fresh_signs = rng.choice(
            np.asarray([-1.0, 1.0], dtype=np.float32),
            size=(batch_size, n_components),
        )
        latent[:, time_index, :] = np.where(resample, fresh_signs, previous)

    observation_flips = (
        rng.random(latent.shape) < observation_flip_probability
    )
    observations = latent * np.where(observation_flips, -1.0, 1.0)
    observations = observations.astype(np.float32, copy=False)

    return (
        observations[:, :-1, :],
        latent[:, 1:, :],
        observations[:, 1:, :],
    )


def optimal_linear_predictor(
    timescale: float,
    observation_flip_probability: float,
    context_length: int,
    jitter: float = 1e-10,
) -> tuple[np.ndarray, float]:
    """Return the optimal finite-context linear filter and its population MSE.

    The history is ordered ``[x_t, x_{t-1}, ..., x_{t-L+1}]``.  Marginal
    observation variance is one.  Off-diagonal autocovariance at lag ``ell``
    is ``(1 - 2 epsilon)^2 rho^ell``.
    """
    if context_length <= 0:
        raise ValueError("context_length must be positive")
    if not 0.0 <= observation_flip_probability <= 0.5:
        raise ValueError("observation_flip_probability must lie in [0, 0.5]")

    rho = timescale_to_pole(timescale)
    reliability = 1.0 - 2.0 * observation_flip_probability
    indices = np.arange(context_length)
    lag_matrix = np.abs(indices[:, None] - indices[None, :])
    covariance = reliability**2 * rho**lag_matrix
    np.fill_diagonal(covariance, 1.0)
    cross_covariance = reliability**2 * rho ** (indices + 1)

    regularized = covariance + jitter * np.eye(context_length)
    weights = np.linalg.solve(regularized, cross_covariance)
    mse = float(1.0 - cross_covariance @ weights)
    return weights, float(np.clip(mse, 0.0, 1.0))


@lru_cache(maxsize=256)
def estimate_bayes_mse(
    timescale: float,
    observation_flip_probability: float,
    *,
    context_length: int = 256,
    n_trajectories: int = 16384,
    seed: int = 0,
) -> float:
    """Estimate finite-context Bayes-optimal next-observation MSE.

    The predictor is exact; Monte Carlo is used only to average its conditional
    risk over stationary latent trajectories and finite observation contexts.
    """
    if n_trajectories <= 0 or context_length <= 0:
        raise ValueError("invalid Monte Carlo dimensions")
    if not 0.0 <= observation_flip_probability <= 0.5:
        raise ValueError("observation_flip_probability must lie in [0, 0.5]")

    rho = timescale_to_pole(timescale)
    resample_probability = 1.0 - rho
    epsilon = float(observation_flip_probability)
    reliability = 1.0 - 2.0 * epsilon
    rng = np.random.default_rng(seed)

    latent = rng.choice(np.asarray([-1.0, 1.0]), size=n_trajectories)
    posterior = np.full(n_trajectories, 0.5, dtype=np.float64)
    for step in range(context_length):
        if step > 0:
            resample = rng.random(n_trajectories) < resample_probability
            fresh = rng.choice(np.asarray([-1.0, 1.0]), size=n_trajectories)
            latent = np.where(resample, fresh, latent)
        flips = rng.random(n_trajectories) < epsilon
        observation = latent * np.where(flips, -1.0, 1.0)

        prior = (
            posterior
            if step == 0
            else rho * posterior + 0.5 * (1.0 - rho)
        )

        like_plus = np.where(observation > 0.0, 1.0 - epsilon, epsilon)
        like_minus = np.where(observation > 0.0, epsilon, 1.0 - epsilon)
        denominator = (
            prior * like_plus
            + (1.0 - prior) * like_minus
        )
        posterior = np.divide(
            prior * like_plus,
            denominator,
            out=np.full_like(prior, 0.5),
            where=denominator > 0.0,
        )

    predictive_posterior = rho * posterior + 0.5 * (1.0 - rho)
    predictive_mean = reliability * (2.0 * predictive_posterior - 1.0)
    return float(np.mean(1.0 - predictive_mean**2))


class MultiscaleHMMOnlineDataset(IterableDataset):
    """Yield online batches from the multiscale symbolic process."""

    def __init__(
        self,
        *,
        num_time_steps: int,
        batch_size: int,
        timescales: list[float],
        observation_flip_probability: float,
        seed: int,
    ) -> None:
        self.num_time_steps = num_time_steps
        self.batch_size = batch_size
        self.timescales = timescales
        self.observation_flip_probability = observation_flip_probability
        self.seed = seed
        self._iterator_count = 0

    def __iter__(self):
        worker = torch.utils.data.get_worker_info()
        worker_offset = 0 if worker is None else worker.id
        # Lightning recreates the iterator at every short pseudo-epoch in the
        # step-budget training loop.  Advance the seed deterministically so
        # those epochs do not replay the same batches.
        iterator_seed = (
            self.seed + worker_offset + 1_000_003 * self._iterator_count
        )
        self._iterator_count += 1
        rng = np.random.default_rng(iterator_seed)
        while True:
            inputs, latent_targets, targets = generate_multiscale_hmm_sequences(
                num_trajectories=self.batch_size,
                num_time_steps=self.num_time_steps,
                timescales=self.timescales,
                observation_flip_probability=self.observation_flip_probability,
                rng=rng,
            )
            yield (
                torch.from_numpy(inputs),
                torch.from_numpy(latent_targets),
                torch.from_numpy(targets),
            )


class MultiscaleHMMDataModule(L.LightningDataModule):
    """Lightning datamodule for multiscale next-symbol prediction."""

    def __init__(
        self,
        n_components: int = 3,
        timescales: float | list[float] = (8.0, 32.0, 128.0),
        observation_flip_probability: float = 0.15,
        num_time_steps: int = 256,
        num_val_trajectories: int = 1024,
        batch_size: int = 128,
        num_workers: int = 4,
        seed: int = 0,
        validation_seed: int = 0,
        prediction_mode: str = "last",
    ) -> None:
        super().__init__()
        if not 0.0 <= observation_flip_probability <= 0.5:
            raise ValueError("observation_flip_probability must lie in [0, 0.5]")
        self.n_components = int(n_components)
        self.timescales = _normalize_timescales(timescales, self.n_components)
        self.observation_flip_probability = float(observation_flip_probability)
        self.num_time_steps = int(num_time_steps)
        self.num_val_trajectories = int(num_val_trajectories)
        self.batch_size = int(batch_size)
        self.num_workers = int(num_workers)
        self.seed = int(seed)
        self.validation_seed = int(validation_seed)
        if prediction_mode not in {"all", "last"}:
            raise ValueError("prediction_mode must be 'all' or 'last'")
        self.prediction_mode = prediction_mode

    def setup(self, stage=None) -> None:
        validation_rng = np.random.default_rng(self.validation_seed)
        inputs, latent_targets, targets = generate_multiscale_hmm_sequences(
            num_trajectories=self.num_val_trajectories,
            num_time_steps=self.num_time_steps,
            timescales=self.timescales,
            observation_flip_probability=self.observation_flip_probability,
            rng=validation_rng,
        )
        self.val_dataset = TensorDataset(
            torch.from_numpy(inputs),
            torch.from_numpy(latent_targets),
            torch.from_numpy(targets),
        )
        self.train_dataset = MultiscaleHMMOnlineDataset(
            num_time_steps=self.num_time_steps,
            batch_size=self.batch_size,
            timescales=self.timescales,
            observation_flip_probability=self.observation_flip_probability,
            seed=self.seed,
        )

    def train_dataloader(self) -> DataLoader:
        return DataLoader(self.train_dataset, batch_size=None, num_workers=0)

    def val_dataloader(self) -> DataLoader:
        return DataLoader(
            self.val_dataset,
            batch_size=self.batch_size,
            num_workers=self.num_workers,
            persistent_workers=self.num_workers > 0,
            shuffle=False,
        )

    @property
    def input_size(self) -> int:
        return self.n_components

    @property
    def output_size(self) -> int:
        return self.n_components

    @property
    def vocabulary_size(self) -> int:
        return 2**self.n_components

    def analysis_metadata(self) -> dict:
        poles = [timescale_to_pole(value) for value in self.timescales]
        linear_losses = []
        linear_filters = []
        bayes_losses = []
        for timescale in self.timescales:
            weights, loss = optimal_linear_predictor(
                timescale,
                self.observation_flip_probability,
                self.num_time_steps,
            )
            linear_filters.append(weights.tolist())
            linear_losses.append(loss)
            bayes_losses.append(
                estimate_bayes_mse(
                    timescale,
                    self.observation_flip_probability,
                    context_length=self.num_time_steps,
                )
            )

        return {
            "task": "multiscale_hmm",
            "description": "noisy multiscale latent-state next-symbol prediction",
            "n_components": self.n_components,
            "vocabulary_size": self.vocabulary_size,
            "component_names": [f"tau_{value:g}" for value in self.timescales],
            "component_groups": [[index] for index in range(self.n_components)],
            "timescales": self.timescales,
            "task_poles_z": poles,
            "resample_probabilities": [1.0 - value for value in poles],
            "observation_flip_probability": self.observation_flip_probability,
            "context_length": self.num_time_steps,
            "prediction_mode": self.prediction_mode,
            "reference_loss_applies_to": "final_position",
            "linear_reference_losses": linear_losses,
            "linear_reference_filters": linear_filters,
            "bayes_reference_losses": bayes_losses,
        }
