# === Project configuration ===
project_name: "path-integration-rnn"
model_type: "multitimescale"
devices: [0, 1, 2, 3] # List of GPU IDs
accelerator: "gpu"
seed: 0 # Global seed


# === RNN configuration == 
input_size: 2 # 3 for sincos HD encoding
hidden_size: 512 #4096
activation: "ReLU" #"Tanh"

# Timescales configuration
timescales_config:
  type: "discrete"
  values: [0.1443] # alpha 0.5
  #values: [0.001, 0.1, 0.2, 0.448, 0.7, 0.9] # corresponds to [1, 0.2] alpha


# === Data (trajectory) configuration ===
trajectory_type: 'ornstein_uhlenbeck'
velocity_representation: 'polar'
dt: 0.1 # s, (reasonable neural dynamics timescale)
num_time_steps: 20
arena_size: 1.1

linear_speed_mean: 0.2
linear_speed_std: 0.5
linear_speed_tau: 1.0
angular_speed_mean: 0.0
angular_speed_std: 1.2
angular_speed_tau: 0.4

# Place cell configuration
num_place_cells: 256
place_cell_rf: 0.2
DoG: true
surround_scale: 2
place_cell_layout: 'random' #'uniform'

# === Training configuration ===
num_trajectories: 100000
train_val_split: 0.8
num_workers: 7
batch_size: 500 #200
learning_rate: 1.0e-4
weight_decay: 1.0e-4
step_size: 100
gamma: 0.5
max_epochs: 200

# === Callback configs ===
decode_k: 3
log_every_n_epochs: 1
viz_log_every_n_epochs: 10

# Checkpoint saving
save_checkpoint_every_n_epochs: 10  # Save checkpoint every N epochs (null or 0 to disable)

# Gradient tracking
grad_log_every_n_steps: 100  # Log gradient stats every N training steps
grad_track_per_weight_matrix: true  # Track W_in, W_rec, W_out separately